stages:
  - build
  - deploy
  - test
  - revert

variables:
  docker_html_path: "/var/www"
  env: prod
  deploy_subfolder: html



install_dependencies:
#  image: node:14.15.0-stretch
  image: node:15.14.0
  #npm install -g npm@7.9.0
  stage: build
  script:
    - yarn install
    - yarn build
    - mv build build_$env
    - node --version
  artifacts:
    paths:
      - node_modules
      - build_$env
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
      

build_staging:
  extends: install_dependencies
  variables:
    env: staging
    REACT_APP_WEBSITE_PREFIX: "[branch=$CI_COMMIT_BRANCH] "
    PUBLIC_URL: "/$CI_COMMIT_BRANCH"

test:
  stage: deploy
#  tags:
#    - stagshell
  script:
    #- cp -r build /www/test-app/$CI_COMMIT_SHA
    - cp -r build $deploy_subfolder/test-app/$CI_COMMIT_SHA
    #- cp -Pv /www/html /www/test-app/$CI_COMMIT_SHA/prev-version
    - cp -Pv /www/html $deploy_subfolder/test-app//$CI_COMMIT_SHA/prev-version
    #- ln -fsnv /var/www/test-app/$CI_COMMIT_SHA /www/html
    - ln -fsnv /var $deploy_subfolder/test-app//$CI_COMMIT_SHA /www/html
  allow_failure: true

deploy_staging:
  extends: deploy_prod
  variables:
    deploy_subfolder: staging/$CI_COMMIT_BRANCH
    env: staging
  when: always
  allow_failure: true
  only:
    - master
    - /feature-.*/

deploy_prod:
  stage: deploy
  script:
    - cp -r build_$env $docker_html_path/test-app/${env}_$CI_COMMIT_SHA
    - ln -fsnv $docker_html_path/test-app/${env}_$CI_COMMIT_BEFORE_SHA $docker_html_path/test-app/${env}_$CI_COMMIT_SHA/prev-version || true
  only:
    - master

activate_staging:
  extends: activate_prod
  variables:
    deploy_subfolder: staging/$CI_COMMIT_BRANCH
    env: staging
  when: always
  only:
    - master
    - /feature-.*/

activate_prod:
  stage: deploy
  script:
    - ln -fsnv /var/www/test-app/${env}_$CI_COMMIT_SHA $docker_html_path/$deploy_subfolder
  when: manual
  only:
    - master

revert:
  stage: revert
  when: manual
  script:
    - rm -rf $docker_html_path/$deploy_subfolder
    - cp -Pv $docker_html_path/test-app/${env}_$CI_COMMIT_BEFORE_SHA/prev-version $docker_html_path/html

#two revert
revert_previous:
  stage: revert
  when: manual
  script:
    - rm -rf $docker_html_path/$deploy_subfolder
    - cp -Pv $docker_html_path/test-app/${env}_$CI_COMMIT_BEFORE_SHA/prev-version $docker_html_path/$deploy_subfolder
